### ISSUE TITLE
plinkLD.py file issue

### ISSUE THREAD

**Issue by tunghup** [shuangsong0110/LDER#1]
Thank you for creating a useful package. When I was trying to use the 'generateLD' function, a minor error happened for the 'plinkLD.py' file. 
The error message was as follows: **Non-ASCII character '\xef' in file ./plinkLD/plinkLD.py on line 258, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details**.
Could you please check it? Thank you in advanced.

**Comment by shuangsong0110** [comment]
Thanks for pointing out this. We have fixed it. Could you please delete the previous "plinkLD.py" file (or the folder "plinkLD") and run "generateLD" function again?

**Comment by tunghup** [comment]
Thank you for the quick response and update. I have re-run the analysis and there is another error in the "plinkMtx.py" file as follows: 
**Traceback (most recent call last):
  File "./plinkLD/plinkLD.py", line 16, in <module>
    import plinkMtx
  File "/data/work/plinkLD/plinkMtx.py", line 8, in <module>
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined**
Thank you again :)

**Comment by shuangsong0110** [comment]
Hi, it seems that it is an error in Python 3.5 (We built it with Python 3.6). One solution would be installing module "plinkio" in advance and see whether the error still occurs. Feel free to contact me if there are further issues.

**Comment by tunghup** [comment]
Hello, the errors do come from my Python installation. I have modified and installed additional required packages and it works successfully. Thank you very much.

**Comment by shuangsong0110** [comment]
Great! You're welcome.
